//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirplaneTracker.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(AirplanesMetadata))]
    public partial class Airplanes
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> AirplaneType { get; set; }
        public Nullable<int> maxpass { get; set; }
        public Nullable<int> size { get; set; }
        public Nullable<int> currentAirport { get; set; }
        //[Display(Name = "current pilot")]
        public Nullable<int> currentpilot { get; set; }
        //[Display(Name = "current copilot")]
        public Nullable<int> currentcopilot { get; set; }
    
        public virtual AirplaneType tblAirplaneType { get; set; }
        public virtual Airports Airports { get; set; }
       // [Display(Name = "current pilot")]
        public virtual pilots tblpilots { get; set; }
       // [Display(Name = "current copilot")]
        public virtual pilots tblpilots1 { get; set; }
        //public int AirportID { get; set; }
    }
    public class AirplanesMetadata
    {
        [Display(Name = "current pilot")]
        public int? currentpilot { get; set; }
        [Display(Name = "current copilot")]
        public int? currentcopilot { get; set; }
    }
}
