//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirplaneTracker.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mvcAssignmentEntities : DbContext
    {
        public mvcAssignmentEntities()
            : base("name=mvcAssignmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Airplanes> Airplanes { get; set; }
        public virtual DbSet<Airports> Airports { get; set; }
        public virtual DbSet<AirplaneType> tblAirplaneType { get; set; }
        public virtual DbSet<pilots> tblpilots { get; set; }
    }
}
